language: node_js

node_js: "latest"

os: osx
osx_image: xcode8

before_script:
    - npm install appium@1.5.3
    - npm install

script:
    - npm run lint
    - npm run test

after_failure:
    - cat appium.log

cache:
  directories:
    - node_modules

notifications:
    email:
        on_success: never
        on_failure: change

