language: node_js

node_js: "6"

os: osx

before_script:
    - npm install appium
    - npm install

script:
    - npm run lint
    - npm run test

after_failure:
    - cat appium.log

cache:
  directories:
    - node_modules

notifications:
    email:
        on_success: never
        on_failure: change

